### PR TITLE
COMPAT: Date before epoch

### LINKED ISSUE #198: COMPAT: return AccessDenied if Date before epochTime (01/01/1970)
On **ceph/s3-tests**, these changes fix:

`FAIL: s3tests.functional.test_headers.test_object_create_bad_date_before_epoch_aws2`
`FAIL: s3tests.functional.test_headers.test_bucket_create_bad_date_before_epoch_aws2`

### PR DESCRIPTION
**Pull request by nicolas2bert**
FIXES #198

### CODE REVIEW

File: lib/auth/v2/checkRequestExpiry.js [hunk 1]
```diff
@@ -1,24 +1,36 @@
 'use strict'; // eslint-disable-line strict
+const errors = require('../../errors');
 
 function checkRequestExpiry(timestamp, log) {
+    const epochTime = new Date('1970-01-01').getTime();
+    // If timestamp is before epochTime, the request is invalid and return
+    // errors.AccessDenied
+    if (timestamp < epochTime) {
+        log.trace('request timestamp is before epochTime');
```
Comment (DavidPineauScality) [inline lib/auth/v2/checkRequestExpiry.js]: we don't need two log entries here, one should suffice.

File: lib/auth/v2/checkRequestExpiry.js [hunk 2]
```diff
@@ -1,24 +1,36 @@
...
 
     if (currentTime + fifteenMinutes < timestamp) {
         log.trace('request timestamp is more than 15 minutes into future');
-        return true;
+        log.debug('request time too skewed', { timestamp });
+        return errors.RequestTimeTooSkewed;
     }
 
-    return false;
+    return {};
```
Comment (DavidPineauScality) [inline lib/auth/v2/checkRequestExpiry.js]: Should we not use "undefined" here, to imply that there's no error, rather than an empty object ?
this looks like counter-intuitive way, that may go against usual "error" management expectations, and lead to errors where the empty object is seen as an error that does not actually say anything,

File: lib/auth/v2/headerAuthCheck.js [hunk 3]
```diff
@@ -21,10 +21,9 @@ function check(request, log, data) {
           'x-amz-date header') };
     }
 
-    const timeout = checkRequestExpiry(timestamp, log);
-    if (timeout) {
-        log.debug('request time too skewed', { timestamp });
-        return { err: errors.RequestTimeTooSkewed };
+    const timeoutResult = checkRequestExpiry(timestamp, log);
```
Comment (DavidPineauScality) [inline lib/auth/v2/headerAuthCheck.js]: following my previous comment, this could be changed into:
```
const err = checkRequestExpiry(timestamp, log);
if (err) {
    return { err } ; // Uses the shorthand syntax for the wrapping (not necessary)
}
```

File: tests/unit/auth/v2/checkRequestExpiry.js [hunk 4]
```diff
@@ -5,25 +5,36 @@ const assert = require('assert');
...
+        assert.deepEqual(timeoutResult, errors.RequestTimeTooSkewed);
     });
 
-    it('should return false if the date in the header is ' +
+    it('should return no error if the date in the header is ' +
        'within 15 minutes of current time', () => {
         const timestamp = new Date();
-        assert(!checkRequestExpiry(timestamp, log));
+        const timeoutResult = checkRequestExpiry(timestamp, log);
+        assert(timeoutResult, {});
```
Comment (DavidPineauScality) [inline tests/unit/auth/v2/checkRequestExpiry.js]: to be changed if you follow my previous comments

File: lib/auth/v2/checkRequestExpiry.js (hunk 2 above)
Comment (nicolas2bert) [inline lib/auth/v2/checkRequestExpiry.js]: Got it! Thanks for the advice.

**Comment by nicolas2bert** [comment]
@ironman-machine ok

File: lib/auth/v2/checkRequestExpiry.js [hunk 5]
```diff
@@ -1,24 +1,35 @@
 'use strict'; // eslint-disable-line strict
+const errors = require('../../errors');
 
 function checkRequestExpiry(timestamp, log) {
+    const epochTime = new Date('1970-01-01').getTime();
```
Comment (michael-zapata) [inline lib/auth/v2/checkRequestExpiry.js]: We can have this as a global instead, meaning we don't create it every time we go in this function.

File: tests/unit/auth/v2/checkRequestExpiry.js [hunk 6]
```diff
@@ -5,25 +5,36 @@ const assert = require('assert');
...
+        const timeoutResult = checkRequestExpiry(timestamp, log);
+        assert.deepEqual(timeoutResult, errors.AccessDenied);
+    });
+
+    it('should return RequestTimeTooSkewed error if the date in the ' +
+       'header is more than 15 minutes old', () => {
         const timestamp = new Date(Date.now() - 16 * 60000);
-        assert(checkRequestExpiry(timestamp, log));
+        const timeoutResult = checkRequestExpiry(timestamp, log);
+        assert.deepEqual(timeoutResult, errors.RequestTimeTooSkewed);
```
Comment (michael-zapata) [inline tests/unit/auth/v2/checkRequestExpiry.js]: `deepStrictEqual()` would be better.

File: lib/auth/v2/checkRequestExpiry.js (hunk 5 above)
Comment (nicolas2bert) [inline lib/auth/v2/checkRequestExpiry.js]: Agree.

File: tests/unit/auth/v2/checkRequestExpiry.js (hunk 6 above)
Comment (nicolas2bert) [inline tests/unit/auth/v2/checkRequestExpiry.js]: Why not.

**Comment by nicolas2bert** [comment]
@ironman-machine ok2

**Comment by nicolas2bert** [comment]
@ironman-machine ok3

**Comment by nicolas2bert** [comment]
@ironman-machine ok4
