### PR TITLE
Compat: Check for invalid Authorization header

### LINKED ISSUE #178: invalid Authorization header: errors incompatible with AWS
When invalid `Authorization` header : return errors which are incompatible with AWS.

These ceph/s3-tests are failing:

```
FAIL: s3tests.functional.test_headers.test_object_create_bad_authorization_invalid_aws2
FAIL: s3tests.functional.test_headers.test_object_create_bad_authorization_invalid_aws4
FAIL: s3tests.functional.test_headers.test_bucket_create_bad_authorization_invalid_aws2
FAIL: s3tests.functional.test_headers.test_bucket_create_bad_authorization_invalid_aws4
```

### PR DESCRIPTION
**Pull request by nicolas2bert**
Fixes #178 

When invalid Authorization header : return InvalidArgument error
AWS checks `authorization` header before `x-amz-content-sha256`
**On [ceph/s3-tests](https://github.com/ceph/s3-tests), these changes fix**:
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_authorization_invalid_aws2`
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_authorization_invalid_aws4`
- `FAIL: s3tests.functional.test_headers.test_bucket_create_bad_authorization_invalid_aws2`
- `FAIL: s3tests.functional.test_headers.test_bucket_create_bad_authorization_invalid_aws4`

### CODE REVIEW

File: lib/auth/v4/headerAuthCheck.js [hunk 1]
```diff
@@ -29,6 +29,11 @@ function check(request, log, data, awsService) {
         return { err: errors.MissingSecurityHeader };
     }
 
+    const authHeaderItems = extractAuthItems(authHeader, log);
+    if (Object.keys(authHeaderItems).length < 3) {
+        return { err: errors.InvalidArgument };
```
Comment (michael-zapata) [inline lib/auth/v4/headerAuthCheck.js]: How about a debug log in there?

Comment (nicolas2bert) [inline lib/auth/v4/headerAuthCheck.js]: Done
